version: 2.0

jobs:
  build:
    environment:
      _JAVA_OPTIONS: "-Xmx3g"
    docker:
      - image: openjdk:8u181-jdk-stretch
    steps:
      - checkout
      - restore_cache:
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - restore_cache:
          key: v1-gradle-cache-{{ checksum "build.gradle" }}
      - run: ./gradlew buildZip
      - save_cache:
          paths:
            - ~/.gradle/wrapper
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - save_cache:
          paths:
            - ~/.gradle/caches
          key: v1-gradle-cache-{{ checksum "build.gradle" }}
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
#      - test:
#          requires:
#            - lint
