version: 2.0

jobs:
  build:
    docker:
      - image: openjdk:8u181-jdk-stretch
    steps:
      - checkout
      - run: java -version
      - run: ./gradlew buildZip

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
#      - test:
#          requires:
#            - lint
